import pandas as pd
import os

# --- CONFIGURATION ---
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Source: The unified log generated by the cross-reference engine
INPUT_FILE = os.path.join(BASE_DIR, 'data', 'processed', 'unified_legislation_log.xlsx')
# Destination paths for both output reports
OUTPUT_FILE = os.path.join(BASE_DIR, 'data', 'processed', 'user_friendly_summary_he.xlsx')
ENFORCEMENT_FILE = os.path.join(BASE_DIR, 'data', 'processed', 'enforcement_action_log.xlsx')

def create_friendly_summary():
    """
    Reads the unified log and creates a simplified, styled Hebrew Excel report.
    Includes logic to consolidate RIA status and surface submission links.
    """
    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(INPUT_FILE)

    # Load data from the unified Excel file
    df = pd.read_excel(INPUT_FILE)

    # 1. Logic: Consolidate RIA Status (Hierarchy: Submission -> Portal)
    def simplify_ria(row):
        # Helper to check if a cell has a positive flag (Hebrew/English) or a URL
        def has_val(val):
            v = str(val).lower().strip()
            return v in ['yes', 'true', 'כן'] or (len(v) > 5 and 'http' in v)

        # Extract values from both sources
        sub_exemption = row.get('RIA_Submission_Exemption_Exists_Flag')
        sub_full_ria = row.get('RIA_Submission_Full_Report_URL')

        portal_exemption = row.get('RIA_Portal_Exemption_URL')
        portal_full_ria = row.get('RIA_Portal_Exists_Flag')

        # Priority 1 & 2: Official Submission
        if has_val(sub_exemption):
            return "קיים פטור"
        if has_val(sub_full_ria):
            return "קיים RIA"

        # Priority 3 & 4: Portal Data (Only if submission is empty)
        if has_val(portal_exemption):
            return "קיים פטור"
        if has_val(portal_full_ria):
            return "קיים RIA"

        # Default: No data found
        return "לא קיים RIA או פטור"

    df['Simplified_RIA_Flag'] = df.apply(simplify_ria, axis=1)

    ## 2. Column Mapping: {Source_Column: Target_Hebrew_Header}
    column_mapping = {
        'unique_url_regulation': 'מזהה קישור ייחודי',
        'נושא': 'נושא',
        'סיכום AI': 'סיכום AI',
        'Responsible_Ministry': 'המשרד האחראי',
        'Regulation_Title': 'שם התקנה/חוק',
        'Portal_Web_Page': 'קישור לדף החקיקה',
        'Processing_Status': 'מקור הנתונים',
        'Associated_Regulations_Count': 'מספר תיקוני חקיקה דומים המשויכים לאותו דוח',
        'Submission_Date': 'תאריך פנייה רשמית',
        'Portal_Publish_Date': 'תאריך פרסום באתר',
        'Simplified_RIA_Flag': 'האם קיים RIA/פטור',
        'RIA_Submission_Full_Report_URL': 'קישור לדוח RIA (פנייה)',
        'Significant_Economic_Impact': 'השפעה משקית',
        'Economic_Impact_Justification': 'נימוק להשפעה',
        'Legislation_Type': 'סוג החקיקה',  # הועבר לסוף
        'Portal_Description': 'תיאור התקנה'  # הועבר לסוף
    }

    # Create an empty 'Portal_Subjects' column so it appears blank in the Excel
    df['Portal_Subjects'] = ""

    # Filter only relevant columns defined in the mapping
    existing_cols = [c for c in column_mapping.keys() if c in df.columns]
    summary_df = df[existing_cols].copy()

    # --- 2.4 Convert date columns to ISO format ---
    date_cols_to_convert = ['Submission_Date', 'Portal_Publish_Date']
    for col in date_cols_to_convert:
        if col in summary_df.columns:
            summary_df[col] = pd.to_datetime(summary_df[col], format='mixed', dayfirst=True,
                                             errors='coerce').dt.strftime('%Y-%m-%d')

    # --- 2.5 Logic: Sort by the earliest available date (OUTSIDE the loop) ---
    temp_dates = summary_df[['Submission_Date', 'Portal_Publish_Date']].apply(pd.to_datetime, format='mixed',
                                                                              dayfirst=True, errors='coerce')
    summary_df['temp_min_date'] = temp_dates.min(axis=1)
    summary_df.sort_values(by='temp_min_date', ascending=True, inplace=True, na_position='last')
    summary_df.drop(columns=['temp_min_date'], inplace=True)

    # --- 2.6 Rename headers to Hebrew ---
    summary_df.rename(columns=column_mapping, inplace=True)

    # 3. Value Translation: Map technical statuses to Hebrew descriptions
    status_map = {
        'Verified Match': 'מאוחד (פורטל + פנייה)',
        'Official Submission Only': 'פנייה רשמית בלבד',
        'Portal Entry Only': 'אתר החקיקה בלבד',
        'Successfully Merged': 'מאוחד (בהצלחה)',
        'Submission (Unverified)': 'פנייה (לא אומתה)'
    }
    if 'מקור הנתונים' in summary_df.columns:
        summary_df['מקור הנתונים'] = summary_df['מקור הנתונים'].replace(status_map)

        # Exact Hebrew mapping based on strict regulatory classification specifications
        legislation_map = {
            'Primary Legislation': 'חקיקה ראשית',
            'Secondary Legislation': 'חקיקה משנית',
            'Support Test': 'מבחני תמיכה',
            'Other': 'אחר'
        }
        if 'סוג החקיקה' in summary_df.columns:
            # Fills empty values or unmapped states with 'אחר' natively before applying the strict map
            summary_df['סוג החקיקה'] = summary_df['סוג החקיקה'].fillna('Other').replace(legislation_map)

            # =========================================================================
            # 3.5 Add New Custom AI-Driven Columns
            # =========================================================================

            def determine_classification(row):
                ai_summary = str(row.get('סיכום AI', '')).strip()

                # Added checks for "צורף פטור" or "צורף דוח"
                if ai_summary.startswith("זו רגולציה") or ai_summary.startswith("צורף פטור") or ai_summary.startswith(
                        "צורף דוח"):
                    return "אסדרה סיווג ראשוני"
                elif ai_summary.startswith("זו אינה רגולציה"):
                    return "לא אסדרה סיווג ראשוני"
                else:
                    return ""

            summary_df['סיווג אסדרה (AI)'] = summary_df.apply(determine_classification, axis=1)

    # 4. Excel Generation and Styling
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with pd.ExcelWriter(OUTPUT_FILE, engine='xlsxwriter') as writer:
        summary_df.to_excel(writer, index=False, sheet_name='Summary')

        workbook = writer.book
        worksheet = writer.sheets['Summary']

        # Layout: Right-to-Left (RTL)
        worksheet.right_to_left()

        # Formatting: Header Style
        header_fmt = workbook.add_format({
            'bold': True,
            'bg_color': '#305496',
            'font_color': 'white',
            'border': 1,
            'align': 'center',
            'valign': 'vcenter'
        })

        # Formatting: Cell Style (No Text Wrap for uniform height)
        cell_fmt = workbook.add_format({
            'align': 'right',
            'valign': 'vcenter',
            'text_wrap': False,
            'border': 1
        })

        # Formatting: Pink background for RIA rows
        pink_fmt = workbook.add_format({
            'bg_color': '#FFC0CB',
            'align': 'right',
            'valign': 'vcenter',
            'border': 1
        })

        # Apply header format and layout properties manually
        for col_num, value in enumerate(summary_df.columns.values):
            worksheet.write(0, col_num, value, header_fmt)

        # Re-mapped explicit column widths based on the new layout architecture (shifted for unique key)
        worksheet.set_column('A:A', 30, cell_fmt)  # מזהה קישור ייחודי
        worksheet.set_column('B:B', 25, cell_fmt)  # נושא
        worksheet.set_column('C:C', 50, cell_fmt)  # סיכום AI
        worksheet.set_column('D:E', 30, cell_fmt)  # המשרד האחראי, שם התקנה/חוק
        worksheet.set_column('F:N', 20, cell_fmt)  # קישורים, מקור, מספר תיקונים, תאריכים, האם קיים RIA, נימוקים
        worksheet.set_column('O:O', 28, cell_fmt)  # סוג החקיקה
        worksheet.set_column('P:P', 60, cell_fmt)  # תיאור התקנה
        worksheet.set_column('Q:Q', 22, cell_fmt)  # סיווג אסדרה

        # Shifted to Column K ($K2) because of the new column insertion upstream
        worksheet.conditional_format('A2:Q1000', {
            'type': 'formula',
            'criteria': '=$K2="קיים RIA"',
            'format': pink_fmt
        })

        # Freeze the top header row for easier scrolling
        worksheet.freeze_panes(1, 0)

        # =========================================================================
        # STEP 5: Generate Secondary Enforcement Action Report
        # =========================================================================
        print("\n[*] PHASE 5: Generating Targeted Enforcement Action Log...")

        # Condition 1: Data source must be exactly 'אתר החקיקה בלבד'
        cond_source = summary_df['מקור הנתונים'] == 'אתר החקיקה בלבד'

        # Condition 2: Portal Publish Date must be older than 14 days from today
        # Parse the text strings back into real timestamps for dynamic duration calculations
        parsed_portal_dates = pd.to_datetime(summary_df['תאריך פרסום באתר'], errors='coerce')
        days_elapsed = (pd.Timestamp.now() - parsed_portal_dates).dt.days
        cond_days = days_elapsed >= 14

        # Condition 3: Must explicitly contain 'קיים RIA' or 'קיים פטור'
        cond_ria = summary_df['האם קיים RIA/פטור'].isin(['קיים RIA', 'קיים פטור'])

        # Bind all constraints together to filter the dataset cleanly
        enforcement_df = summary_df[cond_source & cond_days & cond_ria].copy()
        print(f"    -> Filter criteria matched {len(enforcement_df)} enforcement-eligible rows.")

        # Write and style the Enforcement Action Excel Report natively
        with pd.ExcelWriter(ENFORCEMENT_FILE, engine='xlsxwriter') as enf_writer:
            enforcement_df.to_excel(enf_writer, index=False, sheet_name='Enforcement_Audit')

            enf_workbook = enf_writer.book
            enf_worksheet = enf_writer.sheets['Enforcement_Audit']

            # Enforce right-to-left layout matching the core template layout
            enf_worksheet.right_to_left()

            # Instantiate identical font and layout format metrics
            enf_header_fmt = enf_workbook.add_format({
                'bold': True, 'bg_color': '#305496', 'font_color': 'white',
                'border': 1, 'align': 'center', 'valign': 'vcenter'
            })
            enf_cell_fmt = enf_workbook.add_format({
                'align': 'right', 'valign': 'vcenter', 'text_wrap': False, 'border': 1
            })
            enf_pink_fmt = enf_workbook.add_format({
                'bg_color': '#FFC0CB', 'align': 'right', 'valign': 'vcenter', 'border': 1
            })

            # Render uniform header row block layout matrix
            for col_num, value in enumerate(enforcement_df.columns.values):
                enf_worksheet.write(0, col_num, value, enf_header_fmt)

            # Mirroring the identical column widths for the enforcement log layout (shifted for unique key)
            enf_worksheet.set_column('A:A', 30, enf_cell_fmt)  # מזהה קישור ייחודי
            enf_worksheet.set_column('B:B', 25, enf_cell_fmt)  # נושא
            enf_worksheet.set_column('C:C', 50, enf_cell_fmt)  # סיכום AI
            enf_worksheet.set_column('D:E', 30, enf_cell_fmt)  # המשרד האחראי, שם התקנה/חוק
            enf_worksheet.set_column('F:N', 20,
                                     enf_cell_fmt)  # קישורים, מקור, מספר תיקונים, תאריכים, האם קיים RIA, נימוקים
            enf_worksheet.set_column('O:O', 28, enf_cell_fmt)  # סוג החקיקה
            enf_worksheet.set_column('P:P', 60, enf_cell_fmt)  # תיאור התקנה
            enf_worksheet.set_column('Q:Q', 22, enf_cell_fmt)  # סיווג אסדרה

            # Shifted to Column K ($K2) because of the new column insertion upstream
            enf_worksheet.conditional_format('A2:Q1000', {
                'type': 'formula',
                'criteria': '=$K2="קיים RIA"',
                'format': enf_pink_fmt
            })

            # Apply top header freeze row plane architecture
            enf_worksheet.freeze_panes(1, 0)

        print(f"[*] SUCCESS! Core Summary generated at: {OUTPUT_FILE}")
        print(f"[*] SUCCESS! Targeted Enforcement Log generated at: {ENFORCEMENT_FILE}")

if __name__ == "__main__":
    create_friendly_summary()
